### ISSUE TITLE
Where is gfo-basic.owl?

### ISSUE THREAD

**Issue by k00ni** [Onto-Med/GFO#11]
Hello, I couldn't find mentioned `gfo-basic.owl` file in this repository. Is it located somewhere else?

**Comment by ChristophB** [comment]
Hi, thank you for this remark.
The current version of `gfo-basic.owl` is located at https://www.onto-med.de/ontologies/gfo-basic.owl and is currently not included in this repository. We will discuss in our team whether we should add it.

**Comment by k00ni** [comment]
Thank you for getting back to me so quick.

> We will discuss in our team whether we should add it.

May I ask which role Github plays regarding publishing GFO ontology? Is this repository more like a place to just download OWL files? Or do you / the team plans to develop it here?
