### ISSUE TITLE
Do your OWL-files reflect latest state of GFO development?

### ISSUE THREAD

**Issue by k00ni** [Onto-Med/GFO#13]
I would like to use the GFO and its axioms / classes / ... in a research project. After browsing `gfo-basic.owl` and `gfo.owl` using Protégé I found that some classes (e.g. Stuff or Complex Concrete Individual) are missing, which are mentioned in the (latest GFO?) paper

```
LOEBE, Frank; BUREK, Patryk; HERRE, Heinrich. 
GFO: The General Formal Ontology. 
Applied Ontology, 2022, Nr. Preprint, S. 1-36.
```
[DOI: 10.3233/AO-220264](http://dx.doi.org/10.3233/AO-220264)

![Bildschirmfoto von 2023-04-12 09-45-10](https://user-images.githubusercontent.com/381727/231388441-3bb6e64e-56e0-4185-81e3-7f99559ec704.png)

In the README.md you wrote, that developing GFO is a continuous effort as well as:

> gfo-basic.owl forms the core of the coming releases. We are going to continually provide several extensions to gfo-basic.owl, dedicated to several of our research domains, like time, space, processes, etc.

* Can I assume that the files in this repository reflect the latest development state? If so, why can't I find the class (or category?) `Stuff` anywhere, which is mentioned in the paper above? 
* As a GFO consumer, I would also like to know on which parts (as in files or GFO in general) I can rely on and which obstacles I have to keep in mind. 
* Finally, there are a lot of axioms listed in some papers, like the one above or `BAUMANN, Ringo; LOEBE, Frank; HERRE, Heinrich. Axiomatic theories of the ontology of time in GFO. Applied Ontology, 2014, 9. Jg., Nr. 3-4, S. 171-215.` Are they only represented as a OWL class or is there a plain list of these axioms/FOL-theory somewhere?

I appreciate the work you guys are doing. Thanks for your time in advance!

_PS: I work with Prof. Herre in the KI-Werk-Projekt at IMISE (Uni-Leipzig)._

**Comment by ChristophB** [comment]
The latest version is currently only available as a *light* version. See `gfo-light.owl`.

I have tried to provide a more usable version in the [update-iri-and-use-purl](https://github.com/Onto-Med/GFO/tree/update-iri-and-use-purl) branch. Work on switching to a proper license is also on the way.

As I am not a GFO developer, just helping them set up a development flow and release artifacts, I have to wait for a final review.

Your bullet points have been converted into individual issues. I will now close this (admittedly very long open) issue.
