### ISSUE TITLE
Review license

### ISSUE THREAD

**Issue by ChristophB** [Onto-Med/GFO#18]
Is the currently used license appropriate? Maybe switch to something like CC BY.

The license is also included in the OWL file and should be updated there too.

**Comment by KonradHoeffner** [comment]
P.S.: I just noticed this as I wanted to fill out the "license" field of CITATION.cff,
According to <https://citation-file-format.github.io/cff-initializer-javascript/#/license>, one needs to write down the SPDX license identifier but I don't think the current license has one.
