### ISSUE TITLE
Add workflow to check consistency with reasoning

### ISSUE THREAD

**Issue by ChristophB** [Onto-Med/GFO#22]
There is a workflow to check OWL syntax. It would be nice to also perform reasoning and test for ontology consistency.

**Comment by AlexU75** [comment]
http://owl.cs.manchester.ac.uk/tools/list-of-reasoners/

**Comment by k00ni** [comment]
https://github.com/k00ni/owl-reasoner-list :)

**Comment by ChristophB** [comment]
Another option would be [Robot](http://robot.obolibrary.org/) with two useful commands:
- [report](http://robot.obolibrary.org/report)
- [reason](http://robot.obolibrary.org/reason)
